[dependencies]
jsonrpc-core = '15.1.0'
futures = { version = "0.3.9", features = ["compat"] }
structopt = { version = "0.3.8", optional = true }

[dependencies.frame-benchmarking]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '3.0.0'

[dependencies.frame-benchmarking-cli]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '3.0.0'
optional = true

[dependencies.node-inspect]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '0.8.0'
optional = true

[dependencies.try-runtime-cli]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '0.9.0'
optional = true

[dependencies.acuity-runtime]
path = '../runtime'
version = '2.0.0'

[dependencies.node-executor]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '2.0.0'

[target.'cfg(target_arch="x86_64")'.dependencies.node-executor]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '2.0.0'
features = [ "wasmtime" ]

[dependencies.node-rpc]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '2.0.0'

[dependencies.node-primitives]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '2.0.0'

[dependencies.pallet-contracts]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '2.0.0'

[dependencies.pallet-contracts-rpc]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '0.8.1'

[dependencies.pallet-im-online]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '3.0.0'

[dependencies.pallet-transaction-payment-rpc]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '3.0.0'

[dependencies.sc-authority-discovery]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '0.9.0'

[dependencies.sc-finality-grandpa-warp-sync]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '0.9.0'
optional = true

[dependencies.sc-basic-authorship]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '0.9.0'

[dependencies.sc-cli]
features = ['wasmtime']
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '0.9.0'
optional = true

[dependencies.sc-client-api]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '3.0.0'

[dependencies.sc-consensus]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '0.9.0'

[dependencies.sc-consensus-babe]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '0.9.0'

[dependencies.sc-consensus-slots]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '0.9.0'

[dependencies.sc-executor]
features = ['wasmtime']
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '0.9.0'

[dependencies.sc-finality-grandpa]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '0.9.0'

[dependencies.sc-keystore]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '3.0.0'

[dependencies.sc-network]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '0.9.0'

[dependencies.sc-rpc]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '3.0.0'

[dependencies.sc-rpc-api]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '0.9.0'

[dependencies.sc-service]
features = ['wasmtime']
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '0.9.0'

[dependencies.sc-telemetry]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '3.0.0'

[dependencies.sc-transaction-pool]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '3.0.0'

[dependencies.sp-api]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '3.0.0'

[dependencies.sp-authority-discovery]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '3.0.0'

[dependencies.sp-block-builder]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '3.0.0'

[dependencies.sp-blockchain]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '3.0.0'

[dependencies.sp-consensus]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '0.9.0'

[dependencies.sp-consensus-babe]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '0.9.0'

[dependencies.sp-core]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '3.0.0'

[dependencies.sp-finality-grandpa]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '3.0.0'

[dependencies.sp-inherents]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '3.0.0'

[dependencies.sp-runtime]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '3.0.0'

[dependencies.sp-transaction-pool]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '3.0.0'

[dependencies.substrate-frame-rpc-system]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '3.0.0'

[build-dependencies.substrate-build-script-utils]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '3.0.0'
optional = true

[build-dependencies.substrate-frame-cli]
git = 'https://github.com/paritytech/substrate.git'
branch = "polkadot-v0.8.29"
version = '3.0.0'
optional = true

[[bin]]
name = 'acuity'

[features]
default = [ "cli" ]
cli = [
	"node-executor/wasmi-errno",
	"node-inspect",
	"sc-cli",
	"frame-benchmarking-cli",
	"substrate-frame-cli",
	"sc-service/db",
	"sc-finality-grandpa-warp-sync",
	"structopt",
	"substrate-build-script-utils",
	"try-runtime-cli",
]
runtime-benchmarks = [
	"acuity-runtime/runtime-benchmarks",
	"frame-benchmarking-cli",
]
# Enable features that allow the runtime to be tried and debugged. Name might be subject to change
# in the near future.
try-runtime = [
	"acuity-runtime/try-runtime",
	"try-runtime-cli",
]

[package]
authors = ['Anonymous']
build = 'build.rs'
description = "Implementation of an Acuity node in Rust based on the Substrate framework."
edition = '2018'
homepage = 'https://acuity.social'
license = 'Unlicense'
name = 'acuity'
repository = 'https://github.com/paritytech/substrate/'
version = '2.0.0'
[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']
